# Generated by Django 5.1.7 on 2025-04-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameIndex(
            model_name='comments',
            new_name='blog_commen_created_ad0231_idx',
            old_name='blog_commen_created_0e6ed4_idx',
        ),
    ]
