# Generated by Django 5.1.7 on 2025-05-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_trigram_ext'),
        ('blog', '0007_post_tags'),
    ]

    operations = [
    ]
