# Generated by Django 5.1.7 on 2025-05-14 09:59

from django.contrib.postgres.operations import TrigramExtension # Импортируем расширение Trigram
from django.db import migrations # Импортируем миграции


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_merge_0005_trigram_ext_0007_post_tags'),
    ]

    operations = [
        TrigramExtension(),  # Добавляем расширение Trigram
    ]
